name: Build iOS IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install CocoaPods
        run: |
          cd ios
          pod install
          cd ..

      - name: Build IPA
        run: |
          flutter build ipa --export-options-plist=ios/ExportOptions.plist
        env:
          FLUTTER_BUILD_NAME: ${{ github.run_number }}
          FLUTTER_BUILD_NUMBER: ${{ github.run_id }}

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
